### PR TITLE
Return actual hash algorithm from GPGME adapter

### LINKED ISSUE #107: Return correct hash algorithm name from GPGME adapter
Augments #101 in context of GPGME adapter. The actual algorithm name should be returned instead of "pgp-sha1".

### PR DESCRIPTION
**Pull request by skalee**
Fixes #107. Algorithm preference should be set in a `gpg.conf` file.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @skalee !

**Comment by skalee** [comment]
I got no idea why CodeCov reports are so negative. Perhaps re-running that will change something.

**Comment by ronaldtse** [comment]
@skalee happy to have it merged as long as it works. CodeCov is not always accurate anyway.

**Comment by skalee** [comment]
CodeCov is accurate here. I've switched from high-level API to mid-level one by copy-pasting few of code from gpgme gem. The untested part is two lines in exception handling, and because this pull request is concentrated on just few methods, this is enough to impact codecov/patch report drastically.

Nevertheless, this is not critical. I'll add a comment and merge.

**Comment by ronaldtse** [comment]
Got it. Thanks @skalee !

**Pull request merged**
