### PR TITLE
WIP:Add message signing using adapter

### PR DESCRIPTION
**Pull request by abunashir**
@ronaldtse this is not fully done, but could you please have a look so it would be easier for us to discuss if we are going on the right direction on the development?

This is not a fully completed PR, this will eventually add all the behavior related to the email signing, This just to demonstrate how the actual implementation might be, but nothing in this one is final yet.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@abunashir should this be merged in now?

**Comment by abunashir** [comment]
@ronaldtse: Didn't have a chance to work on it since the last update, I will merge it once we start working on this again.

**Comment by ronaldtse** [comment]
@skalee perhaps it would be wise to first merge this? Thanks!

**Comment by ronaldtse** [comment]
@skalee any thoughts?

**Comment by skalee** [comment]
@ronaldtse Sorry, I've overlooked this one. I have some work-in-progress related to enmail on my computer. I'll recap it tomorrow.

**Comment by ronaldtse** [comment]
@skalee just would like to check if this could be completed soon, our RNP Ruby binding will be ready by next week (https://github.com/riboseinc/ruby-rnp) and therefore ready for putting into an adapter. Thanks!

**Comment by ronaldtse** [comment]
@skalee @abunashir it might be easiest if we first merge this and handle #21 ?

**Comment by abunashir** [comment]
@ronaldtse: It's been a while since I worked on this, and I not sure how Sebastian is planning for this library. @skalee Could you please share your high-level plan for this moving forward?

**Comment by skalee** [comment]
It is very good, but indeed I've changed the architecture totally and I am not going to merge it (as of now). I'll elaborate tomorrow.

**Comment by skalee** [comment]
Sorry for late response.

There are several reasons why I haven't merged this pull request in, and probably won't.  I'm not closing it yet though, just in case.

First of all, this pull request addresses S/MIME whereas I decided to start with GPGME.  Although the former is way simpler, the latter should allow with easier transition to RNP as they're both about Open PGP.  Also, one of the gems (mail-gpg) actually is about GPGME signing and initially I wanted to use it as an example.

Furthermore, architecture proposed in this pull request will be insufficient for sure.  Although it separates signing algorithms with concept of "adapters" in a very clean way, the differences between S/MIME and Open PGP are much deeper.  For example, in Open PGP message conforms to RFC 1847 "Security Multiparts for MIME", whereas S/MIME does not.  That results in different message layout, which need to be handled in adapter as well.  I understand that current architecture was experimental, and the idea behind was to bring quickly at least S/MIME support, then iterate, and iterate again.  However if I start with GPGME support instead, that work-in-progress architecture would be quite a burden.

**Comment by ronaldtse** [comment]
You’re right on the points, this is indeed to start off an iteration process using S/MIME which is much simpler to do. 

The issue with mail-gpg is it contains hacky code into ActionMailer and does not have a clean abstraction — as you probably already realized, we decided early on to re-implement it’s functionality, and at most incorporate only certain parts of mail-gpg. 

Look forward to the updated approach!

**Comment by skalee** [comment]
I believe we can close it now.

**Comment by ronaldtse** [comment]
Excellent news @skalee ! Could you also help update the README on how to use the GnuPG adapter (eg import/unlock keys, select key for signing/encryption)? Thanks.

**Comment by skalee** [comment]
@ronaldtse There's #32 about README improvements already.

Regarding importing private key for signing into keyring, there's no such feature, and I guess there'll never be. IMHO it should be done with ordinary GPG tools.

Regarding key unlocking, it is addressed in #39, which doesn't pass tests on Travis at this moment, unfortunately. Reasons described in the pull request.

**Comment by ronaldtse** [comment]
@skalee it's a little hard to figure out how the new flow works, so I'll leave my comments after the README is done.

Anyway, in our case, keys are not provided via a keyring file, but loaded via a database. The only way GnuPG can use them is to first import into a keyring. However, RNP is designed to work with a case like this. Maybe we need this gem (or some GPGME wrapper) to support multiple, temporary homedirs for the usage of importing, signing, and forgetting the key.

**Pull request closed without merging**
