### PR TITLE
Test against compatible GnuPG versions

### PR DESCRIPTION
**Pull request by skalee**
Test against GPG version 2.1, and version 2.2. The EnMail won't work with GPG version 2.0, which is available by default in Ubuntu Trusty.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@skalee from the commits I see you're almost there! Any updates so far? Thanks!

**Comment by skalee** [comment]
@ronaldtse More less there. I'll update over the weekend. For now, I'd rather like to leave this one for a day or two, and start fixing riboseinc/rails_encrypted_token.

**Comment by ronaldtse** [comment]
Excellent, thanks @skalee !

**Comment by ronaldtse** [comment]
@skalee seems that we're fetching from the FTP server. Their packages are also available via HTTP here: https://gnupg.org/download/index.html and would work much better than FTP.

The HTTP links looks like this: https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.8.tar.bz2

**Comment by ronaldtse** [comment]
@skalee are we ready to merge this? Thanks!

**Comment by skalee** [comment]
@ronaldtse Version from Git won't compile easily, unfortunately. This is due to outdated packages in Trusty, notably gettext which has to be compiled from source. Apart from that, I guess so. Scripts are in https://github.com/riboseinc/gpg-build-scripts. Bash is the language.

**Comment by ronaldtse** [comment]
@skalee this PR is building fine. Is it ready to be merged? Thanks!

**Comment by skalee** [comment]
It was passing, then it was failing for GnuPG 2.1 again (probably after merging #57 in).

In order to close this one, I've removed problematic GnuPG version from build matrix, and created an issue to fix it later (#64).

**Comment by skalee** [comment]
The GnuPG 2.1 issues are to be continued in #65.

**Pull request merged**
